include ../../Makefile.common

override CPPFLAGS += -I../../include -DNDEBUG
ifeq ($(OS),Darwin)
  override LDFLAGS += -L../../lib
else
  override LDFLAGS += -L../../lib -static
endif

LDLIBS := -lloki

ifeq ($(OS),Windows)
BIN_SUFFIX := .exe
else
BIN_SUFFIX :=
endif
