

CPP  = g++
CC   = gcc
OBJ  = main.o  
LINKOBJ  = main.o
CXXINCS =  -I./../../include  -I./../../include/loki 
BIN  = main-mingw.exe
CXXFLAGS = $(CXXINCS) -Wall -pedantic -funroll-loops   -fexpensive-optimizations -O2
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before main-mingw.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o main-mingw.exe $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

