

CPP  = g++
CC   = gcc
OBJ  = tmp\main.o  
LINKOBJ  = tmp\main.o
CXXINCS =  -I./../../include
BIN  = main-mingw.exe
CXXFLAGS = $(CXXINCS) -W0 -O2 -DNDEBUG
RM = rm -f
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir

.PHONY: all all-before all-after clean clean-custom

all: all-before check_tmp main-mingw.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o main-mingw.exe $(LIBS)

check_tmp: 
	@$(CHK_DIR_EXISTS) "tmp\" $(MKDIR) "tmp"
	
tmp\main.o: main.cpp
	$(CPP) -c main.cpp -o tmp\main.o $(CXXFLAGS)

