

CPP  = g++
CC   = gcc
OBJ  = SmallObjBench.o SmallObj.o 
LINKOBJ  = SmallObjBench.o SmallObj.o
CXXINCS =  -I./../../include  -I./../../include/loki 
BIN  = main-mingw.exe
CXXFLAGS = $(CXXINCS) -Wall -pedantic -funroll-loops   -fexpensive-optimizations -O2
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before main-mingw.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o main-mingw.exe $(LIBS)

SmallObjBench.o: SmallObjBench.cpp
	$(CPP) -c SmallObjBench.cpp -o SmallObjBench.o $(CXXFLAGS)

SmallObj.o: ../../src/SmallObj.cpp
	$(CPP) -c ../../src/SmallObj.cpp -o SmallObj.o $(CXXFLAGS)
