install:
	mkdir -p $(DESTDIR)/usr/include/loki
	mkdir -p $(DESTDIR)/usr/include/loki/flex
	mkdir -p $(DESTDIR)/usr/include/loki/yasli
	
	install loki/*.h $(DESTDIR)/usr/include/loki
	install loki/flex/*.h $(DESTDIR)/usr/include/loki/flex
	install loki/yasli/*.h $(DESTDIR)/usr/include/loki/yasli
